import './images/banner@1x.webp';
import './images/easy.01749a24.webp';
import './images/fast.36029745.webp';
import './images/ipad.b748c1d5.webp';
import './images/logo.svg';
import './images/sprite.svg';
import './images/support.22f42806.webp';
import './images/test.jpg';
import './images/tick.svg';
import './images/wordpress.c5854b7a.webp';
import './images/Mr.Gathura.jpg';
import './images/popular.svg';
import './css/style.css';
import './css/normalize.css';
import './components/badge.html';
import './components/block.html';
import './components/buttons.html';
import './components/callout.html';
import './components/cards.html';
import collapsibleContent from './components/collapsible.html';
const container = document.createElement('div');
container.innerHTML = collapsibleContent;
document.body.appendChild(container);
import domainblockContent from './components/domain-block.html';
container.innerHTML = domainblockContent;
document.body.appendChild(container);
import featureblockContent from './components/feature-block.html';
container.innerHTML = featureblockContent;
document.body.appendChild(container);
import footerContent from './components/footer.html';
container.innerHTML = footerContent;
document.body.appendChild(container);
import heroContent from './components/hero.html';
container.innerHTML =heroContent;
document.body.appendChild(container);
import iconsContent from './components/icons.html';
container.innerHTML =iconsContent;
document.body.appendChild(container);
import inputgroupContent from './components/input-group.html';
container.innerHTML = inputgroupContent;
document.body.appendChild(container);
import mediaContent from './components/media.html';
container.innerHTML = mediaContent;
document.body.appendChild(container);
import navContent from './components/nav.html';
container.innerHTML =navContent;
document.body.appendChild(container);
import quoteContent from './components/quote.html';
container.innerHTML =quoteContent;
document.body.appendChild(container);
import showcaseblockContent from './components/showcase-block.html';
container.innerHTML =showcaseblockContent;
document.body.appendChild(container);
import testimonialblockContent from './components/testimonial-block.html';
container.innerHTML =testimonialblockContent;
document.body.appendChild(container);
import testimonialContent from './components/testimonial.html';
container.innerHTML =testimonialContent;
document.body.appendChild(container);
import './components/grid.html';
import './components/input.html';
import './components/link-arrow.html';
import './components/list.html';
import './components/plans.html';
import './js/main.js';
